sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t xoals6536/docker-cicd-app -f Dockerfile.dev .
  
script:
  - docker run -e CI=true xoals6536/docker-cicd-app npm run test -- --coverage

after_success:
  - echo "Test Success"